//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Others {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Others() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Others", typeof(Resource_Others).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello to you,
        ///To confirm this email Address as being linked to your {1} Account, please click on the Link below to confirm your Email, or copy and paste it into your favorite Web Browser.
        ///{2}
        ///
        ///Thank you!.
        /// </summary>
        public static string email_ChngEmail {
            get {
                return ResourceManager.GetString("email_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello to you,
        ///
        ///There was a request to change the password of the {1} Account linked to this email address.
        ///If this request was not made by you, please ignore this email, else please click on the Link below to change your password, or copy and paste it into your favorite Web Browser.
        ///{2}
        ///
        ///Thank you!.
        /// </summary>
        public static string email_RstPsswrd {
            get {
                return ResourceManager.GetString("email_RstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello to you Dear Potential User of {1},
        ///If you wish to complete your registration please click on the following link or copy and paste it into your favorite Web Browser.
        ///{2}
        ///
        ///Thank you!.
        /// </summary>
        public static string email_SignUp {
            get {
                return ResourceManager.GetString("email_SignUp", resourceCulture);
            }
        }
    }
}
