//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Msgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Msgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Msgs", typeof(Resource_Msgs).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologogise, but could you check that your internet connection is ok and try again.
        ///Thank you..
        /// </summary>
        public static string errMsg_Aplgs {
            get {
                return ResourceManager.GetString("errMsg_Aplgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} Alphabetical character is required.
        /// </summary>
        public static string errMsg_Pswrd_Alpha {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {1} characters long.
        /// </summary>
        public static string errMsg_Pswrd_MinLen {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_MinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} Numerical character is required.
        /// </summary>
        public static string errMsg_Pswrd_Numeric {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces aren&apos;t allowed in Passwords.
        /// </summary>
        public static string errMsg_Pswrd_Spaces {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} Special character is required.
        /// </summary>
        public static string errMsg_Pswrd_Special {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} Uppercase character is required.
        /// </summary>
        public static string errMsg_Pswrd_Uppercase {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password does not conform to the account password policy.
        /// </summary>
        public static string errMsg_PswrdPolicy {
            get {
                return ResourceManager.GetString("errMsg_PswrdPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record {1} already exists.
        /// </summary>
        public static string errMsg_RecordExists {
            get {
                return ResourceManager.GetString("errMsg_RecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Record.
        /// </summary>
        public static string msg_AddNew {
            get {
                return ResourceManager.GetString("msg_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role {1}.
        /// </summary>
        public static string msg_AddRole {
            get {
                return ResourceManager.GetString("msg_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string msg_ChngEmail {
            get {
                return ResourceManager.GetString("msg_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Change Email.
        /// </summary>
        public static string msg_ClckChngEmail {
            get {
                return ResourceManager.GetString("msg_ClckChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already used.
        /// </summary>
        public static string msg_EmailAlrdUsed {
            get {
                return ResourceManager.GetString("msg_EmailAlrdUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account is attached to &quot;{1}&quot;.
        ///Please try again..
        /// </summary>
        public static string msg_EmailPsswrdNotExists {
            get {
                return ResourceManager.GetString("msg_EmailPsswrdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the same Password as above.
        /// </summary>
        public static string msg_EntrSmPsswrd {
            get {
                return ResourceManager.GetString("msg_EntrSmPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email or username to reset your password:.
        /// </summary>
        public static string msg_FrgtPsswrdDtls {
            get {
                return ResourceManager.GetString("msg_FrgtPsswrdDtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string msg_InvldEmail {
            get {
                return ResourceManager.GetString("msg_InvldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password.
        /// </summary>
        public static string msg_InvldUsrNmPsswrd {
            get {
                return ResourceManager.GetString("msg_InvldUsrNmPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        public static string msg_InvldValue {
            get {
                return ResourceManager.GetString("msg_InvldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Link you are using has expired.
        ///Links have an expirery date as part of Security Measures..
        /// </summary>
        public static string msg_LnkXprd {
            get {
                return ResourceManager.GetString("msg_LnkXprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of {1} characters are required.
        /// </summary>
        public static string msg_MinLenReq {
            get {
                return ResourceManager.GetString("msg_MinLenReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have permission to perform this action..
        /// </summary>
        public static string msg_NoPermission {
            get {
                return ResourceManager.GetString("msg_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a new Password.
        /// </summary>
        public static string msg_PlsNewPsswrd {
            get {
                return ResourceManager.GetString("msg_PlsNewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Successfully Changed.
        /// </summary>
        public static string msg_PsswrdChngSccss {
            get {
                return ResourceManager.GetString("msg_PsswrdChngSccss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password does not meet complexity requirements..
        /// </summary>
        public static string msg_PsswrdNotReq {
            get {
                return ResourceManager.GetString("msg_PsswrdNotReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Complete.
        /// </summary>
        public static string msg_PsswrdRstCmplt {
            get {
                return ResourceManager.GetString("msg_PsswrdRstCmplt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Complete.
        /// </summary>
        public static string msg_RegComplete {
            get {
                return ResourceManager.GetString("msg_RegComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Role {1}.
        /// </summary>
        public static string msg_RemoveRole {
            get {
                return ResourceManager.GetString("msg_RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Confirmation.
        /// </summary>
        public static string msg_ReqConfrmtn {
            get {
                return ResourceManager.GetString("msg_ReqConfrmtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent, in which you will find a link to reset your password..
        /// </summary>
        public static string msg_RstEmailSent {
            get {
                return ResourceManager.GetString("msg_RstEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your {1} password?
        ///
        ///We&apos;ve received a request to reset the password for this email address.
        ///
        ///To reset your password please click on this link or copy and paste this URL into your browser (link expires in 24 hours):
        ///{2}
        ///
        ///This link takes you to a secure page where you can change your password.
        ///
        ///If you don&apos;t want to reset your password, please ignore this message and your password will not be reset..
        /// </summary>
        public static string msg_RstPasswrdEmail {
            get {
                return ResourceManager.GetString("msg_RstPasswrdEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {1}?.
        /// </summary>
        public static string msg_SureDelete {
            get {
                return ResourceManager.GetString("msg_SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image(s).
        /// </summary>
        public static string msg_UploadImgs {
            get {
                return ResourceManager.GetString("msg_UploadImgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already used.
        /// </summary>
        public static string msg_UsrnmAlrdUsed {
            get {
                return ResourceManager.GetString("msg_UsrnmAlrdUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please enter a valid email address.
        /// </summary>
        public static string msg_valEmail {
            get {
                return ResourceManager.GetString("msg_valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Required.
        /// </summary>
        public static string msg_ValReq {
            get {
                return ResourceManager.GetString("msg_ValReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Confirmation for Email.
        /// </summary>
        public static string msg_WtngCnfrmEmail {
            get {
                return ResourceManager.GetString("msg_WtngCnfrmEmail", resourceCulture);
            }
        }
    }
}
