//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Labels", typeof(Resource_Labels).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahita Property - Back Office.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string lbl_Account {
            get {
                return ResourceManager.GetString("lbl_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Detail.
        /// </summary>
        public static string lbl_AccountDetail {
            get {
                return ResourceManager.GetString("lbl_AccountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lbl_Actions {
            get {
                return ResourceManager.GetString("lbl_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lbl_Active {
            get {
                return ResourceManager.GetString("lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string lbl_Active_ {
            get {
                return ResourceManager.GetString("lbl_Active_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactives.
        /// </summary>
        public static string lbl_Active_0 {
            get {
                return ResourceManager.GetString("lbl_Active_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actives.
        /// </summary>
        public static string lbl_Active_1 {
            get {
                return ResourceManager.GetString("lbl_Active_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string lbl_Add {
            get {
                return ResourceManager.GetString("lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Roles.
        /// </summary>
        public static string lbl_AddRmvRoles {
            get {
                return ResourceManager.GetString("lbl_AddRmvRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string lbl_Administrator {
            get {
                return ResourceManager.GetString("lbl_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lbl_Apply {
            get {
                return ResourceManager.GetString("lbl_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appear Detail.
        /// </summary>
        public static string lbl_AprDtl {
            get {
                return ResourceManager.GetString("lbl_AprDtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string lbl_Back {
            get {
                return ResourceManager.GetString("lbl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed Rooms Count.
        /// </summary>
        public static string lbl_BdRmsCnt {
            get {
                return ResourceManager.GetString("lbl_BdRmsCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string lbl_BoRstPsswrd {
            get {
                return ResourceManager.GetString("lbl_BoRstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string lbl_BoValEmail {
            get {
                return ResourceManager.GetString("lbl_BoValEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lbl_Cancel {
            get {
                return ResourceManager.GetString("lbl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Confirm Email Address.
        /// </summary>
        public static string lbl_CantCnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CantCnfrmEmailAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string lbl_CfrmNewPsswrd {
            get {
                return ResourceManager.GetString("lbl_CfrmNewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string lbl_Change {
            get {
                return ResourceManager.GetString("lbl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string lbl_ChngEmail {
            get {
                return ResourceManager.GetString("lbl_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lbl_ChngPsswrd {
            get {
                return ResourceManager.GetString("lbl_ChngPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lbl_Close {
            get {
                return ResourceManager.GetString("lbl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        public static string lbl_CnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CnfrmEmailAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lbl_Code {
            get {
                return ResourceManager.GetString("lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Registration.
        /// </summary>
        public static string lbl_CompleteReg {
            get {
                return ResourceManager.GetString("lbl_CompleteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string lbl_Confirmed {
            get {
                return ResourceManager.GetString("lbl_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string lbl_Continue {
            get {
                return ResourceManager.GetString("lbl_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lbl_Country {
            get {
                return ResourceManager.GetString("lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string lbl_CreateNew {
            get {
                return ResourceManager.GetString("lbl_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string lbl_CreateNwUsr {
            get {
                return ResourceManager.GetString("lbl_CreateNwUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string lbl_CurPsswrd {
            get {
                return ResourceManager.GetString("lbl_CurPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string lbl_Currency {
            get {
                return ResourceManager.GetString("lbl_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lbl_Days {
            get {
                return ResourceManager.GetString("lbl_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string lbl_DeleteUser {
            get {
                return ResourceManager.GetString("lbl_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbl_Desc {
            get {
                return ResourceManager.GetString("lbl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string lbl_Dob {
            get {
                return ResourceManager.GetString("lbl_Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string lbl_Done {
            get {
                return ResourceManager.GetString("lbl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Page.
        /// </summary>
        public static string lbl_DtlPg {
            get {
                return ResourceManager.GetString("lbl_DtlPg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string lbl_Duration {
            get {
                return ResourceManager.GetString("lbl_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lbl_Edit {
            get {
                return ResourceManager.GetString("lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string lbl_EmailConfirmed {
            get {
                return ResourceManager.GetString("lbl_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not Sent.
        /// </summary>
        public static string lbl_EmailNotSent {
            get {
                return ResourceManager.GetString("lbl_EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        public static string lbl_EmailSent {
            get {
                return ResourceManager.GetString("lbl_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent Failed.
        /// </summary>
        public static string lbl_EmailSentFailed {
            get {
                return ResourceManager.GetString("lbl_EmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string lbl_Error {
            get {
                return ResourceManager.GetString("lbl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Saving.
        /// </summary>
        public static string lbl_ErrWhlSvng {
            get {
                return ResourceManager.GetString("lbl_ErrWhlSvng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lbl_FName {
            get {
                return ResourceManager.GetString("lbl_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten Password ?.
        /// </summary>
        public static string lbl_FrgtPsswrd {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string lbl_FrgtPsswrdQm {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrdQm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lbl_Gender {
            get {
                return ResourceManager.GetString("lbl_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string lbl_Gender_0 {
            get {
                return ResourceManager.GetString("lbl_Gender_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string lbl_Gender_10 {
            get {
                return ResourceManager.GetString("lbl_Gender_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string lbl_Gender_20 {
            get {
                return ResourceManager.GetString("lbl_Gender_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Size.
        /// </summary>
        public static string lbl_GrossSize {
            get {
                return ResourceManager.GetString("lbl_GrossSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string lbl_Groups {
            get {
                return ResourceManager.GetString("lbl_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string lbl_Hello {
            get {
                return ResourceManager.GetString("lbl_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide in Website.
        /// </summary>
        public static string lbl_HideInWs {
            get {
                return ResourceManager.GetString("lbl_HideInWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lbl_Inactive {
            get {
                return ResourceManager.GetString("lbl_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string lbl_Langs {
            get {
                return ResourceManager.GetString("lbl_Langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land for Sale.
        /// </summary>
        public static string lbl_Lfs {
            get {
                return ResourceManager.GetString("lbl_Lfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lbl_LName {
            get {
                return ResourceManager.GetString("lbl_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Size.
        /// </summary>
        public static string lbl_LotSize {
            get {
                return ResourceManager.GetString("lbl_LotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Image.
        /// </summary>
        public static string lbl_LstImg {
            get {
                return ResourceManager.GetString("lbl_LstImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        public static string lbl_ManageRoles {
            get {
                return ResourceManager.GetString("lbl_ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string lbl_Menu_dashboard {
            get {
                return ResourceManager.GetString("lbl_Menu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string lbl_Menu_emails {
            get {
                return ResourceManager.GetString("lbl_Menu_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string lbl_Menu_notifications {
            get {
                return ResourceManager.GetString("lbl_Menu_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string lbl_Menu_products {
            get {
                return ResourceManager.GetString("lbl_Menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string lbl_Menu_projects {
            get {
                return ResourceManager.GetString("lbl_Menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string lbl_Menu_properties {
            get {
                return ResourceManager.GetString("lbl_Menu_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string lbl_Menu_usermanagement {
            get {
                return ResourceManager.GetString("lbl_Menu_usermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lbl_Mobile {
            get {
                return ResourceManager.GetString("lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Size.
        /// </summary>
        public static string lbl_NetSize {
            get {
                return ResourceManager.GetString("lbl_NetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lbl_NewPsswrd {
            get {
                return ResourceManager.GetString("lbl_NewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name.
        /// </summary>
        public static string lbl_NoName {
            get {
                return ResourceManager.GetString("lbl_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Confirmed.
        /// </summary>
        public static string lbl_NotConfirmed {
            get {
                return ResourceManager.GetString("lbl_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Room DEN.
        /// </summary>
        public static string lbl_OptnRmDen {
            get {
                return ResourceManager.GetString("lbl_OptnRmDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string lbl_Or {
            get {
                return ResourceManager.GetString("lbl_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Detail.
        /// </summary>
        public static string lbl_PersonalDetail {
            get {
                return ResourceManager.GetString("lbl_PersonalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Numbers.
        /// </summary>
        public static string lbl_PhoneNumbers {
            get {
                return ResourceManager.GetString("lbl_PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string lbl_PostCode {
            get {
                return ResourceManager.GetString("lbl_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lbl_Price {
            get {
                return ResourceManager.GetString("lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string lbl_Prj {
            get {
                return ResourceManager.GetString("lbl_Prj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_Profile {
            get {
                return ResourceManager.GetString("lbl_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_Psswrd {
            get {
                return ResourceManager.GetString("lbl_Psswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string lbl_Refresh {
            get {
                return ResourceManager.GetString("lbl_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string lbl_Request {
            get {
                return ResourceManager.GetString("lbl_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email.
        /// </summary>
        public static string lbl_ResendEmail {
            get {
                return ResourceManager.GetString("lbl_ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string lbl_Retry {
            get {
                return ResourceManager.GetString("lbl_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string lbl_Revert {
            get {
                return ResourceManager.GetString("lbl_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string lbl_RmbrMe {
            get {
                return ResourceManager.GetString("lbl_RmbrMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lbl_Role {
            get {
                return ResourceManager.GetString("lbl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resale.
        /// </summary>
        public static string lbl_Rsl {
            get {
                return ResourceManager.GetString("lbl_Rsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string lbl_RstPsswrd {
            get {
                return ResourceManager.GetString("lbl_RstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lbl_Save {
            get {
                return ResourceManager.GetString("lbl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string lbl_SaveChanges {
            get {
                return ResourceManager.GetString("lbl_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Later.
        /// </summary>
        public static string lbl_SaveLater {
            get {
                return ResourceManager.GetString("lbl_SaveLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string lbl_Saving {
            get {
                return ResourceManager.GetString("lbl_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lbl_Sccss {
            get {
                return ResourceManager.GetString("lbl_Sccss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_Search {
            get {
                return ResourceManager.GetString("lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string lbl_Send {
            get {
                return ResourceManager.GetString("lbl_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string lbl_SendEmail {
            get {
                return ResourceManager.GetString("lbl_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email.
        /// </summary>
        public static string lbl_SendingEmail {
            get {
                return ResourceManager.GetString("lbl_SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lbl_Settings {
            get {
                return ResourceManager.GetString("lbl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short (Listing).
        /// </summary>
        public static string lbl_ShortDesc {
            get {
                return ResourceManager.GetString("lbl_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string lbl_SignIn {
            get {
                return ResourceManager.GetString("lbl_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string lbl_SignOut {
            get {
                return ResourceManager.GetString("lbl_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        public static string lbl_SlctProj {
            get {
                return ResourceManager.GetString("lbl_SlctProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Property.
        /// </summary>
        public static string lbl_SlctProp {
            get {
                return ResourceManager.GetString("lbl_SlctProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string lbl_SmthngWrng {
            get {
                return ResourceManager.GetString("lbl_SmthngWrng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string lbl_Undo {
            get {
                return ResourceManager.GetString("lbl_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string lbl_Unknown {
            get {
                return ResourceManager.GetString("lbl_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile.
        /// </summary>
        public static string lbl_UpdateProfile {
            get {
                return ResourceManager.GetString("lbl_UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string lbl_Upload {
            get {
                return ResourceManager.GetString("lbl_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string lbl_UserManagement {
            get {
                return ResourceManager.GetString("lbl_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lbl_UsrNm {
            get {
                return ResourceManager.GetString("lbl_UsrNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Email.
        /// </summary>
        public static string lbl_UsrNmEmail {
            get {
                return ResourceManager.GetString("lbl_UsrNmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying.
        /// </summary>
        public static string lbl_Verifying {
            get {
                return ResourceManager.GetString("lbl_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string lbl_Views {
            get {
                return ResourceManager.GetString("lbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sub Products.
        /// </summary>
        public static string lbl_VwSubProds {
            get {
                return ResourceManager.GetString("lbl_VwSubProds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string lbl_Warning {
            get {
                return ResourceManager.GetString("lbl_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string lbl_Yes {
            get {
                return ResourceManager.GetString("lbl_Yes", resourceCulture);
            }
        }
    }
}
