//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Labels_FR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Labels_FR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Labels_FR", typeof(Resource_Labels_FR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string lbl_Actions {
            get {
                return ResourceManager.GetString("lbl_Actions", resourceCulture);
            }
        }
        
        public static string lbl_Add {
            get {
                return ResourceManager.GetString("lbl_Add", resourceCulture);
            }
        }
        
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        public static string lbl_Apply {
            get {
                return ResourceManager.GetString("lbl_Apply", resourceCulture);
            }
        }
        
        public static string lbl_Back {
            get {
                return ResourceManager.GetString("lbl_Back", resourceCulture);
            }
        }
        
        public static string lbl_BoValEmail {
            get {
                return ResourceManager.GetString("lbl_BoValEmail", resourceCulture);
            }
        }
        
        public static string lbl_CantCnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CantCnfrmEmailAddr", resourceCulture);
            }
        }
        
        public static string lbl_CfrmNewPsswrd {
            get {
                return ResourceManager.GetString("lbl_CfrmNewPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_ChngEmail {
            get {
                return ResourceManager.GetString("lbl_ChngEmail", resourceCulture);
            }
        }
        
        public static string lbl_ChngPsswrd {
            get {
                return ResourceManager.GetString("lbl_ChngPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_Change {
            get {
                return ResourceManager.GetString("lbl_Change", resourceCulture);
            }
        }
        
        public static string lbl_Close {
            get {
                return ResourceManager.GetString("lbl_Close", resourceCulture);
            }
        }
        
        public static string lbl_CnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CnfrmEmailAddr", resourceCulture);
            }
        }
        
        public static string lbl_Continue {
            get {
                return ResourceManager.GetString("lbl_Continue", resourceCulture);
            }
        }
        
        public static string lbl_CreateNew {
            get {
                return ResourceManager.GetString("lbl_CreateNew", resourceCulture);
            }
        }
        
        public static string lbl_CurPsswrd {
            get {
                return ResourceManager.GetString("lbl_CurPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        public static string lbl_Dob {
            get {
                return ResourceManager.GetString("lbl_Dob", resourceCulture);
            }
        }
        
        public static string lbl_Edit {
            get {
                return ResourceManager.GetString("lbl_Edit", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_EmailConfirmed {
            get {
                return ResourceManager.GetString("lbl_EmailConfirmed", resourceCulture);
            }
        }
        
        public static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        public static string lbl_Error {
            get {
                return ResourceManager.GetString("lbl_Error", resourceCulture);
            }
        }
        
        public static string lbl_ErrWhlSvng {
            get {
                return ResourceManager.GetString("lbl_ErrWhlSvng", resourceCulture);
            }
        }
        
        public static string lbl_FName {
            get {
                return ResourceManager.GetString("lbl_FName", resourceCulture);
            }
        }
        
        public static string lbl_FrgtPsswrdQm {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrdQm", resourceCulture);
            }
        }
        
        public static string lbl_Gender {
            get {
                return ResourceManager.GetString("lbl_Gender", resourceCulture);
            }
        }
        
        public static string lbl_Gender_0 {
            get {
                return ResourceManager.GetString("lbl_Gender_0", resourceCulture);
            }
        }
        
        public static string lbl_Gender_10 {
            get {
                return ResourceManager.GetString("lbl_Gender_10", resourceCulture);
            }
        }
        
        public static string lbl_Gender_20 {
            get {
                return ResourceManager.GetString("lbl_Gender_20", resourceCulture);
            }
        }
        
        public static string lbl_Langs {
            get {
                return ResourceManager.GetString("lbl_Langs", resourceCulture);
            }
        }
        
        public static string lbl_LName {
            get {
                return ResourceManager.GetString("lbl_LName", resourceCulture);
            }
        }
        
        public static string lbl_Menu_dashboard {
            get {
                return ResourceManager.GetString("lbl_Menu_dashboard", resourceCulture);
            }
        }
        
        public static string lbl_Menu_emails {
            get {
                return ResourceManager.GetString("lbl_Menu_emails", resourceCulture);
            }
        }
        
        public static string lbl_Menu_notifications {
            get {
                return ResourceManager.GetString("lbl_Menu_notifications", resourceCulture);
            }
        }
        
        public static string lbl_Menu_usermanagement {
            get {
                return ResourceManager.GetString("lbl_Menu_usermanagement", resourceCulture);
            }
        }
        
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        public static string lbl_NewPsswrd {
            get {
                return ResourceManager.GetString("lbl_NewPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        public static string lbl_NoName {
            get {
                return ResourceManager.GetString("lbl_NoName", resourceCulture);
            }
        }
        
        public static string lbl_Or {
            get {
                return ResourceManager.GetString("lbl_Or", resourceCulture);
            }
        }
        
        public static string lbl_PhoneNumbers {
            get {
                return ResourceManager.GetString("lbl_PhoneNumbers", resourceCulture);
            }
        }
        
        public static string lbl_Profile {
            get {
                return ResourceManager.GetString("lbl_Profile", resourceCulture);
            }
        }
        
        public static string lbl_UpdateProfile {
            get {
                return ResourceManager.GetString("lbl_UpdateProfile", resourceCulture);
            }
        }
        
        public static string lbl_Psswrd {
            get {
                return ResourceManager.GetString("lbl_Psswrd", resourceCulture);
            }
        }
        
        public static string lbl_Refresh {
            get {
                return ResourceManager.GetString("lbl_Refresh", resourceCulture);
            }
        }
        
        public static string lbl_Retry {
            get {
                return ResourceManager.GetString("lbl_Retry", resourceCulture);
            }
        }
        
        public static string lbl_Revert {
            get {
                return ResourceManager.GetString("lbl_Revert", resourceCulture);
            }
        }
        
        public static string lbl_RmbrMe {
            get {
                return ResourceManager.GetString("lbl_RmbrMe", resourceCulture);
            }
        }
        
        public static string lbl_RstPsswrd {
            get {
                return ResourceManager.GetString("lbl_RstPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_Save {
            get {
                return ResourceManager.GetString("lbl_Save", resourceCulture);
            }
        }
        
        public static string lbl_SaveLater {
            get {
                return ResourceManager.GetString("lbl_SaveLater", resourceCulture);
            }
        }
        
        public static string lbl_Saving {
            get {
                return ResourceManager.GetString("lbl_Saving", resourceCulture);
            }
        }
        
        public static string lbl_Sccss {
            get {
                return ResourceManager.GetString("lbl_Sccss", resourceCulture);
            }
        }
        
        public static string lbl_Send {
            get {
                return ResourceManager.GetString("lbl_Send", resourceCulture);
            }
        }
        
        public static string lbl_SendEmail {
            get {
                return ResourceManager.GetString("lbl_SendEmail", resourceCulture);
            }
        }
        
        public static string lbl_Settings {
            get {
                return ResourceManager.GetString("lbl_Settings", resourceCulture);
            }
        }
        
        public static string lbl_SignIn {
            get {
                return ResourceManager.GetString("lbl_SignIn", resourceCulture);
            }
        }
        
        public static string lbl_SignOut {
            get {
                return ResourceManager.GetString("lbl_SignOut", resourceCulture);
            }
        }
        
        public static string lbl_SmthngWrng {
            get {
                return ResourceManager.GetString("lbl_SmthngWrng", resourceCulture);
            }
        }
        
        public static string lbl_Unknown {
            get {
                return ResourceManager.GetString("lbl_Unknown", resourceCulture);
            }
        }
        
        public static string lbl_UsrNm {
            get {
                return ResourceManager.GetString("lbl_UsrNm", resourceCulture);
            }
        }
        
        public static string lbl_UsrNmEmail {
            get {
                return ResourceManager.GetString("lbl_UsrNmEmail", resourceCulture);
            }
        }
        
        public static string lbl_Verifying {
            get {
                return ResourceManager.GetString("lbl_Verifying", resourceCulture);
            }
        }
        
        public static string lbl_Website {
            get {
                return ResourceManager.GetString("lbl_Website", resourceCulture);
            }
        }
        
        public static string lbl_Yes {
            get {
                return ResourceManager.GetString("lbl_Yes", resourceCulture);
            }
        }
        
        public static string lbl_Role {
            get {
                return ResourceManager.GetString("lbl_Role", resourceCulture);
            }
        }
        
        public static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        public static string lbl_Duration {
            get {
                return ResourceManager.GetString("lbl_Duration", resourceCulture);
            }
        }
        
        public static string lbl_Days {
            get {
                return ResourceManager.GetString("lbl_Days", resourceCulture);
            }
        }
        
        public static string lbl_Active {
            get {
                return ResourceManager.GetString("lbl_Active", resourceCulture);
            }
        }
        
        public static string lbl_Inactive {
            get {
                return ResourceManager.GetString("lbl_Inactive", resourceCulture);
            }
        }
        
        public static string lbl_Active_ {
            get {
                return ResourceManager.GetString("lbl_Active_", resourceCulture);
            }
        }
        
        public static string lbl_Active_0 {
            get {
                return ResourceManager.GetString("lbl_Active_0", resourceCulture);
            }
        }
        
        public static string lbl_Active_1 {
            get {
                return ResourceManager.GetString("lbl_Active_1", resourceCulture);
            }
        }
        
        public static string lbl_Cancel {
            get {
                return ResourceManager.GetString("lbl_Cancel", resourceCulture);
            }
        }
        
        public static string lbl_Request {
            get {
                return ResourceManager.GetString("lbl_Request", resourceCulture);
            }
        }
        
        public static string lbl_Hello {
            get {
                return ResourceManager.GetString("lbl_Hello", resourceCulture);
            }
        }
        
        public static string lbl_Confirmed {
            get {
                return ResourceManager.GetString("lbl_Confirmed", resourceCulture);
            }
        }
        
        public static string lbl_NotConfirmed {
            get {
                return ResourceManager.GetString("lbl_NotConfirmed", resourceCulture);
            }
        }
        
        public static string lbl_AddRmvRoles {
            get {
                return ResourceManager.GetString("lbl_AddRmvRoles", resourceCulture);
            }
        }
        
        public static string lbl_CreateNwUsr {
            get {
                return ResourceManager.GetString("lbl_CreateNwUsr", resourceCulture);
            }
        }
        
        public static string lbl_Done {
            get {
                return ResourceManager.GetString("lbl_Done", resourceCulture);
            }
        }
        
        public static string lbl_EmailNotSent {
            get {
                return ResourceManager.GetString("lbl_EmailNotSent", resourceCulture);
            }
        }
        
        public static string lbl_EmailSent {
            get {
                return ResourceManager.GetString("lbl_EmailSent", resourceCulture);
            }
        }
        
        public static string lbl_ResendEmail {
            get {
                return ResourceManager.GetString("lbl_ResendEmail", resourceCulture);
            }
        }
        
        public static string lbl_EmailSentFailed {
            get {
                return ResourceManager.GetString("lbl_EmailSentFailed", resourceCulture);
            }
        }
        
        public static string lbl_SendingEmail {
            get {
                return ResourceManager.GetString("lbl_SendingEmail", resourceCulture);
            }
        }
        
        public static string lbl_CompleteReg {
            get {
                return ResourceManager.GetString("lbl_CompleteReg", resourceCulture);
            }
        }
        
        public static string lbl_Search {
            get {
                return ResourceManager.GetString("lbl_Search", resourceCulture);
            }
        }
        
        public static string lbl_SaveChanges {
            get {
                return ResourceManager.GetString("lbl_SaveChanges", resourceCulture);
            }
        }
        
        public static string lbl_PersonalDetail {
            get {
                return ResourceManager.GetString("lbl_PersonalDetail", resourceCulture);
            }
        }
        
        public static string lbl_Account {
            get {
                return ResourceManager.GetString("lbl_Account", resourceCulture);
            }
        }
        
        public static string lbl_AccountDetail {
            get {
                return ResourceManager.GetString("lbl_AccountDetail", resourceCulture);
            }
        }
        
        public static string lbl_Mobile {
            get {
                return ResourceManager.GetString("lbl_Mobile", resourceCulture);
            }
        }
        
        public static string lbl_Country {
            get {
                return ResourceManager.GetString("lbl_Country", resourceCulture);
            }
        }
        
        public static string lbl_PostCode {
            get {
                return ResourceManager.GetString("lbl_PostCode", resourceCulture);
            }
        }
        
        public static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        public static string lbl_Administrator {
            get {
                return ResourceManager.GetString("lbl_Administrator", resourceCulture);
            }
        }
        
        public static string lbl_ManageRoles {
            get {
                return ResourceManager.GetString("lbl_ManageRoles", resourceCulture);
            }
        }
        
        public static string lbl_DeleteUser {
            get {
                return ResourceManager.GetString("lbl_DeleteUser", resourceCulture);
            }
        }
        
        public static string lbl_Warning {
            get {
                return ResourceManager.GetString("lbl_Warning", resourceCulture);
            }
        }
        
        public static string lbl_BoRstPsswrd {
            get {
                return ResourceManager.GetString("lbl_BoRstPsswrd", resourceCulture);
            }
        }
        
        public static string lbl_UserManagement {
            get {
                return ResourceManager.GetString("lbl_UserManagement", resourceCulture);
            }
        }
        
        public static string lbl_Menu_products {
            get {
                return ResourceManager.GetString("lbl_Menu_products", resourceCulture);
            }
        }
        
        public static string lbl_Menu_projects {
            get {
                return ResourceManager.GetString("lbl_Menu_projects", resourceCulture);
            }
        }
        
        public static string lbl_Menu_properties {
            get {
                return ResourceManager.GetString("lbl_Menu_properties", resourceCulture);
            }
        }
        
        public static string lbl_GrossSize {
            get {
                return ResourceManager.GetString("lbl_GrossSize", resourceCulture);
            }
        }
        
        public static string lbl_NetSize {
            get {
                return ResourceManager.GetString("lbl_NetSize", resourceCulture);
            }
        }
        
        public static string lbl_Price {
            get {
                return ResourceManager.GetString("lbl_Price", resourceCulture);
            }
        }
        
        public static string lbl_Currency {
            get {
                return ResourceManager.GetString("lbl_Currency", resourceCulture);
            }
        }
        
        public static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        public static string lbl_HideInWs {
            get {
                return ResourceManager.GetString("lbl_HideInWs", resourceCulture);
            }
        }
        
        public static string lbl_FrgtPsswrd {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrd", resourceCulture);
            }
        }
    }
}
