//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Others_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Others_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Others_FR", typeof(Resource_Others_FR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour à vous,
        ///Pour confirmer cette adresse Email comme étant la nouvelle Adresse Liée à votre Compte de {1}, cliquer sur le lien plus bas, ou copiez et collez le lien dans votre Navigateur Web préféré.
        ///{2}
        ///
        ///Merci!.
        /// </summary>
        public static string email_ChngEmail {
            get {
                return ResourceManager.GetString("email_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour à vous,
        ///
        ///Une requête a été émise pour changer le mot de passe du compte {1} lié à cette adresse email. Si cette requête n’a pas été émise par vous, veuillez svp ignorer ce courriel, sinon cliquez sur le lien plus bas, ou copiez et collez le lien dans votre Navigateur Web préféré.
        ///{2}
        ///
        ///Merci!.
        /// </summary>
        public static string email_RstPsswrd {
            get {
                return ResourceManager.GetString("email_RstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour à vous cher Potetiel Utilisateur de {1},
        ///Pour compléter l&apos;enregistrement de ce Compte {1}, cliquer sur le lien plus bas, ou copiez et collez le lien dans votre Navigateur Web préféré.
        ///{2}
        ///
        ///Merci!.
        /// </summary>
        public static string email_SignUp {
            get {
                return ResourceManager.GetString("email_SignUp", resourceCulture);
            }
        }
    }
}
