//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Msgs_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Msgs_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Msgs_FR", typeof(Resource_Msgs_FR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous présentons nos excuses, mais pourriez-vous vérifier que votre connexion internet marche bien et réessayez.
        ///Merci.
        /// </summary>
        public static string errMsg_Aplgs {
            get {
                return ResourceManager.GetString("errMsg_Aplgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min de {1} caractère Alphabétique est requis.
        /// </summary>
        public static string errMsg_Pswrd_Alpha {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min de {1} caractères.
        /// </summary>
        public static string errMsg_Pswrd_MinLen {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_MinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min de {1} caractère Numérique est requis.
        /// </summary>
        public static string errMsg_Pswrd_Numeric {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Espaces ne sont pas authorisé dans les mots-de-passe.
        /// </summary>
        public static string errMsg_Pswrd_Spaces {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min de {1} caractère &apos;Spécial&apos; est requis.
        /// </summary>
        public static string errMsg_Pswrd_Special {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min de {1} caractère Majuscule est requis.
        /// </summary>
        public static string errMsg_Pswrd_Uppercase {
            get {
                return ResourceManager.GetString("errMsg_Pswrd_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe n’est pas conforme aux exigences de complexités.
        /// </summary>
        public static string errMsg_PswrdPolicy {
            get {
                return ResourceManager.GetString("errMsg_PswrdPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La donnée {1} existe déjà.
        /// </summary>
        public static string errMsg_RecordExists {
            get {
                return ResourceManager.GetString("errMsg_RecordExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une Nouvelle donnée.
        /// </summary>
        public static string msg_AddNew {
            get {
                return ResourceManager.GetString("msg_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter le Rôle {1}.
        /// </summary>
        public static string msg_AddRole {
            get {
                return ResourceManager.GetString("msg_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer l&apos;adresse Email.
        /// </summary>
        public static string msg_ChngEmail {
            get {
                return ResourceManager.GetString("msg_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez pour changer le Email.
        /// </summary>
        public static string msg_ClckChngEmail {
            get {
                return ResourceManager.GetString("msg_ClckChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet adresse Email est déjà utilisée.
        /// </summary>
        public static string msg_EmailAlrdUsed {
            get {
                return ResourceManager.GetString("msg_EmailAlrdUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun compte n&apos;est attaché à &quot;{1}&quot;.
        ///Veuillez réessayer..
        /// </summary>
        public static string msg_EmailPsswrdNotExists {
            get {
                return ResourceManager.GetString("msg_EmailPsswrdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez re-entrer le mot de passe choisi plus haut.
        /// </summary>
        public static string msg_EntrSmPsswrd {
            get {
                return ResourceManager.GetString("msg_EntrSmPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre email ou votre nom d&apos;utilisateur pour réinitialiser votre mot de passe:.
        /// </summary>
        public static string msg_FrgtPsswrdDtls {
            get {
                return ResourceManager.GetString("msg_FrgtPsswrdDtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalide.
        /// </summary>
        public static string msg_InvldEmail {
            get {
                return ResourceManager.GetString("msg_InvldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;Utilisateur ou Mot de Passe Invalide!.
        /// </summary>
        public static string msg_InvldUsrNmPsswrd {
            get {
                return ResourceManager.GetString("msg_InvldUsrNmPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lien que vous utilisez a expiré.
        ///Certains de nos liens ont des dates d&apos;expirations pour des mesures de sécurité..
        /// </summary>
        public static string msg_LnkXprd {
            get {
                return ResourceManager.GetString("msg_LnkXprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un minimum de {1} caractères sont requis.
        /// </summary>
        public static string msg_MinLenReq {
            get {
                return ResourceManager.GetString("msg_MinLenReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez disposer d&apos;une autorisation pour effectuer cette action..
        /// </summary>
        public static string msg_NoPermission {
            get {
                return ResourceManager.GetString("msg_NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez svp utiliser un nouveau mot de passe.
        /// </summary>
        public static string msg_PlsNewPsswrd {
            get {
                return ResourceManager.GetString("msg_PlsNewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de Passe changé avec succès.
        /// </summary>
        public static string msg_PsswrdChngSccss {
            get {
                return ResourceManager.GetString("msg_PsswrdChngSccss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe n&apos;est pas conforme aux exigences de sécurité.
        /// </summary>
        public static string msg_PsswrdNotReq {
            get {
                return ResourceManager.GetString("msg_PsswrdNotReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation du mot de passe complétée.
        /// </summary>
        public static string msg_PsswrdRstCmplt {
            get {
                return ResourceManager.GetString("msg_PsswrdRstCmplt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement Terminé.
        /// </summary>
        public static string msg_RegComplete {
            get {
                return ResourceManager.GetString("msg_RegComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirer le Rôle {1}.
        /// </summary>
        public static string msg_RemoveRole {
            get {
                return ResourceManager.GetString("msg_RemoveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiert une confirmation.
        /// </summary>
        public static string msg_ReqConfrmtn {
            get {
                return ResourceManager.GetString("msg_ReqConfrmtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un email a été envoyé dans lequel vous trouverez un lien pour réinitialiser votre mot de passe..
        /// </summary>
        public static string msg_RstEmailSent {
            get {
                return ResourceManager.GetString("msg_RstEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez oublié votre mot de passe pour {1}.
        ///
        ///Nous avons reçu une requête pour changer votre mot de passe de cette adresse Email.
        ///Pour le changer, cliquez sur le lien ci-dessous ou copier-coller le lien dans votre navigateur internet. (Le lien expire dans 24 heures)
        ///{2}
        ///
        ///Ce lien vous mènera vers une page sécurisée d’où vous pourrez changer votre mot de passe.
        ///
        ///Si vous ne voulez pas changer votre mot de passe, ignorez ce message..
        /// </summary>
        public static string msg_RstPasswrdEmail {
            get {
                return ResourceManager.GetString("msg_RstPasswrdEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sure de vouloir supprimer {1}?.
        /// </summary>
        public static string msg_SureDelete {
            get {
                return ResourceManager.GetString("msg_SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet Identifiant est déjà utilisé.
        /// </summary>
        public static string msg_UsrnmAlrdUsed {
            get {
                return ResourceManager.GetString("msg_UsrnmAlrdUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Veuillez s&apos;il vous plaît entrer une address email valide.
        /// </summary>
        public static string msg_valEmail {
            get {
                return ResourceManager.GetString("msg_valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur Requise.
        /// </summary>
        public static string msg_ValReq {
            get {
                return ResourceManager.GetString("msg_ValReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de confirmation pour le Email.
        /// </summary>
        public static string msg_WtngCnfrmEmail {
            get {
                return ResourceManager.GetString("msg_WtngCnfrmEmail", resourceCulture);
            }
        }
    }
}
