//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnahitaProp.BackOffice.Localization.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Labels_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Labels_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnahitaProp.BackOffice.Localization.Resources.Resource_Labels_FR", typeof(Resource_Labels_FR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahita Property - Back Office.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte.
        /// </summary>
        public static string lbl_Account {
            get {
                return ResourceManager.GetString("lbl_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail du Compte.
        /// </summary>
        public static string lbl_AccountDetail {
            get {
                return ResourceManager.GetString("lbl_AccountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string lbl_Actions {
            get {
                return ResourceManager.GetString("lbl_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actif.
        /// </summary>
        public static string lbl_Active {
            get {
                return ResourceManager.GetString("lbl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout.
        /// </summary>
        public static string lbl_Active_ {
            get {
                return ResourceManager.GetString("lbl_Active_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactifs.
        /// </summary>
        public static string lbl_Active_0 {
            get {
                return ResourceManager.GetString("lbl_Active_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actifs.
        /// </summary>
        public static string lbl_Active_1 {
            get {
                return ResourceManager.GetString("lbl_Active_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string lbl_Add {
            get {
                return ResourceManager.GetString("lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une nouvelle Famille.
        /// </summary>
        public static string lbl_AddNewFam {
            get {
                return ResourceManager.GetString("lbl_AddNewFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string lbl_Address {
            get {
                return ResourceManager.GetString("lbl_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter/Retirer Roles.
        /// </summary>
        public static string lbl_AddRmvRoles {
            get {
                return ResourceManager.GetString("lbl_AddRmvRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrateur.
        /// </summary>
        public static string lbl_Administrator {
            get {
                return ResourceManager.GetString("lbl_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer.
        /// </summary>
        public static string lbl_Apply {
            get {
                return ResourceManager.GetString("lbl_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparaît sur Détail.
        /// </summary>
        public static string lbl_AprDtl {
            get {
                return ResourceManager.GetString("lbl_AprDtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string lbl_Back {
            get {
                return ResourceManager.GetString("lbl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Chambres.
        /// </summary>
        public static string lbl_BdRmsCnt {
            get {
                return ResourceManager.GetString("lbl_BdRmsCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser le mot de passe.
        /// </summary>
        public static string lbl_BoRstPsswrd {
            get {
                return ResourceManager.GetString("lbl_BoRstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation de l&apos;Email.
        /// </summary>
        public static string lbl_BoValEmail {
            get {
                return ResourceManager.GetString("lbl_BoValEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string lbl_Cancel {
            get {
                return ResourceManager.GetString("lbl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de Confirmer l&apos;adresse Email.
        /// </summary>
        public static string lbl_CantCnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CantCnfrmEmailAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez le Mot de Passe.
        /// </summary>
        public static string lbl_CfrmNewPsswrd {
            get {
                return ResourceManager.GetString("lbl_CfrmNewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer.
        /// </summary>
        public static string lbl_Change {
            get {
                return ResourceManager.GetString("lbl_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer le Email.
        /// </summary>
        public static string lbl_ChngEmail {
            get {
                return ResourceManager.GetString("lbl_ChngEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer votre Mot de Passe.
        /// </summary>
        public static string lbl_ChngPsswrd {
            get {
                return ResourceManager.GetString("lbl_ChngPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string lbl_Close {
            get {
                return ResourceManager.GetString("lbl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer l&apos;adresse Email.
        /// </summary>
        public static string lbl_CnfrmEmailAddr {
            get {
                return ResourceManager.GetString("lbl_CnfrmEmailAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lbl_Code {
            get {
                return ResourceManager.GetString("lbl_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completer l&apos;Enregistrement.
        /// </summary>
        public static string lbl_CompleteReg {
            get {
                return ResourceManager.GetString("lbl_CompleteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmé.
        /// </summary>
        public static string lbl_Confirmed {
            get {
                return ResourceManager.GetString("lbl_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string lbl_Continue {
            get {
                return ResourceManager.GetString("lbl_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string lbl_Country {
            get {
                return ResourceManager.GetString("lbl_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer Nouveau.
        /// </summary>
        public static string lbl_CreateNew {
            get {
                return ResourceManager.GetString("lbl_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel Utilisateur.
        /// </summary>
        public static string lbl_CreateNwUsr {
            get {
                return ResourceManager.GetString("lbl_CreateNwUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de Passe Actuel.
        /// </summary>
        public static string lbl_CurPsswrd {
            get {
                return ResourceManager.GetString("lbl_CurPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string lbl_Currency {
            get {
                return ResourceManager.GetString("lbl_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jours.
        /// </summary>
        public static string lbl_Days {
            get {
                return ResourceManager.GetString("lbl_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string lbl_Delete {
            get {
                return ResourceManager.GetString("lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer Utilisateur.
        /// </summary>
        public static string lbl_DeleteUser {
            get {
                return ResourceManager.GetString("lbl_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbl_Desc {
            get {
                return ResourceManager.GetString("lbl_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDN.
        /// </summary>
        public static string lbl_Dob {
            get {
                return ResourceManager.GetString("lbl_Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer.
        /// </summary>
        public static string lbl_Done {
            get {
                return ResourceManager.GetString("lbl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Détail.
        /// </summary>
        public static string lbl_DtlPg {
            get {
                return ResourceManager.GetString("lbl_DtlPg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée.
        /// </summary>
        public static string lbl_Duration {
            get {
                return ResourceManager.GetString("lbl_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string lbl_Edit {
            get {
                return ResourceManager.GetString("lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse email Confirmée.
        /// </summary>
        public static string lbl_EmailConfirmed {
            get {
                return ResourceManager.GetString("lbl_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email pas envoyé.
        /// </summary>
        public static string lbl_EmailNotSent {
            get {
                return ResourceManager.GetString("lbl_EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email envoyé.
        /// </summary>
        public static string lbl_EmailSent {
            get {
                return ResourceManager.GetString("lbl_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoi d&apos;Email échoué.
        /// </summary>
        public static string lbl_EmailSentFailed {
            get {
                return ResourceManager.GetString("lbl_EmailSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de Fin.
        /// </summary>
        public static string lbl_EndDate {
            get {
                return ResourceManager.GetString("lbl_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string lbl_Error {
            get {
                return ResourceManager.GetString("lbl_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de sauvegarde échouée.
        /// </summary>
        public static string lbl_ErrWhlSvng {
            get {
                return ResourceManager.GetString("lbl_ErrWhlSvng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille.
        /// </summary>
        public static string lbl_Family {
            get {
                return ResourceManager.GetString("lbl_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string lbl_FName {
            get {
                return ResourceManager.GetString("lbl_FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string lbl_FrgtPsswrd {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string lbl_FrgtPsswrdQm {
            get {
                return ResourceManager.GetString("lbl_FrgtPsswrdQm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string lbl_Gender {
            get {
                return ResourceManager.GetString("lbl_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string lbl_Gender_0 {
            get {
                return ResourceManager.GetString("lbl_Gender_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homme.
        /// </summary>
        public static string lbl_Gender_10 {
            get {
                return ResourceManager.GetString("lbl_Gender_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femme.
        /// </summary>
        public static string lbl_Gender_20 {
            get {
                return ResourceManager.GetString("lbl_Gender_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension Brute.
        /// </summary>
        public static string lbl_GrossSize {
            get {
                return ResourceManager.GetString("lbl_GrossSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe.
        /// </summary>
        public static string lbl_Group {
            get {
                return ResourceManager.GetString("lbl_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupes.
        /// </summary>
        public static string lbl_Groups {
            get {
                return ResourceManager.GetString("lbl_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour.
        /// </summary>
        public static string lbl_Hello {
            get {
                return ResourceManager.GetString("lbl_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacher sur le Site Web.
        /// </summary>
        public static string lbl_HideInWs {
            get {
                return ResourceManager.GetString("lbl_HideInWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactif.
        /// </summary>
        public static string lbl_Inactive {
            get {
                return ResourceManager.GetString("lbl_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        public static string lbl_Langs {
            get {
                return ResourceManager.GetString("lbl_Langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain à bâtir.
        /// </summary>
        public static string lbl_Lfs {
            get {
                return ResourceManager.GetString("lbl_Lfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string lbl_LName {
            get {
                return ResourceManager.GetString("lbl_LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface du Lot.
        /// </summary>
        public static string lbl_LotSize {
            get {
                return ResourceManager.GetString("lbl_LotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Liste.
        /// </summary>
        public static string lbl_LstImg {
            get {
                return ResourceManager.GetString("lbl_LstImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les rôles.
        /// </summary>
        public static string lbl_ManageRoles {
            get {
                return ResourceManager.GetString("lbl_ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de Bord.
        /// </summary>
        public static string lbl_Menu_dashboard {
            get {
                return ResourceManager.GetString("lbl_Menu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string lbl_Menu_emails {
            get {
                return ResourceManager.GetString("lbl_Menu_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string lbl_Menu_notifications {
            get {
                return ResourceManager.GetString("lbl_Menu_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produits.
        /// </summary>
        public static string lbl_Menu_products {
            get {
                return ResourceManager.GetString("lbl_Menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projets.
        /// </summary>
        public static string lbl_Menu_projects {
            get {
                return ResourceManager.GetString("lbl_Menu_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriétées.
        /// </summary>
        public static string lbl_Menu_properties {
            get {
                return ResourceManager.GetString("lbl_Menu_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des Utilisateurs.
        /// </summary>
        public static string lbl_Menu_usermanagement {
            get {
                return ResourceManager.GetString("lbl_Menu_usermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lbl_Mobile {
            get {
                return ResourceManager.GetString("lbl_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension Net.
        /// </summary>
        public static string lbl_NetSize {
            get {
                return ResourceManager.GetString("lbl_NetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Mot de Passe.
        /// </summary>
        public static string lbl_NewPsswrd {
            get {
                return ResourceManager.GetString("lbl_NewPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de Nom.
        /// </summary>
        public static string lbl_NoName {
            get {
                return ResourceManager.GetString("lbl_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Confirmé.
        /// </summary>
        public static string lbl_NotConfirmed {
            get {
                return ResourceManager.GetString("lbl_NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Chambres DEN.
        /// </summary>
        public static string lbl_OptnRmDen {
            get {
                return ResourceManager.GetString("lbl_OptnRmDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou.
        /// </summary>
        public static string lbl_Or {
            get {
                return ResourceManager.GetString("lbl_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail Personnel.
        /// </summary>
        public static string lbl_PersonalDetail {
            get {
                return ResourceManager.GetString("lbl_PersonalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string lbl_PhoneNumbers {
            get {
                return ResourceManager.GetString("lbl_PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string lbl_PostCode {
            get {
                return ResourceManager.GetString("lbl_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lbl_Price {
            get {
                return ResourceManager.GetString("lbl_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        public static string lbl_Prj {
            get {
                return ResourceManager.GetString("lbl_Prj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_Profile {
            get {
                return ResourceManager.GetString("lbl_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de Passe.
        /// </summary>
        public static string lbl_Psswrd {
            get {
                return ResourceManager.GetString("lbl_Psswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraichir.
        /// </summary>
        public static string lbl_Refresh {
            get {
                return ResourceManager.GetString("lbl_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande.
        /// </summary>
        public static string lbl_Request {
            get {
                return ResourceManager.GetString("lbl_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-envoyer le Email.
        /// </summary>
        public static string lbl_ResendEmail {
            get {
                return ResourceManager.GetString("lbl_ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        public static string lbl_Retry {
            get {
                return ResourceManager.GetString("lbl_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restorer.
        /// </summary>
        public static string lbl_Revert {
            get {
                return ResourceManager.GetString("lbl_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se souvenir de moi.
        /// </summary>
        public static string lbl_RmbrMe {
            get {
                return ResourceManager.GetString("lbl_RmbrMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôle.
        /// </summary>
        public static string lbl_Role {
            get {
                return ResourceManager.GetString("lbl_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revente.
        /// </summary>
        public static string lbl_Rsl {
            get {
                return ResourceManager.GetString("lbl_Rsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation du mot de passe.
        /// </summary>
        public static string lbl_RstPsswrd {
            get {
                return ResourceManager.GetString("lbl_RstPsswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string lbl_Save {
            get {
                return ResourceManager.GetString("lbl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder Modifications.
        /// </summary>
        public static string lbl_SaveChanges {
            get {
                return ResourceManager.GetString("lbl_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder plus tard.
        /// </summary>
        public static string lbl_SaveLater {
            get {
                return ResourceManager.GetString("lbl_SaveLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde.
        /// </summary>
        public static string lbl_Saving {
            get {
                return ResourceManager.GetString("lbl_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succès.
        /// </summary>
        public static string lbl_Sccss {
            get {
                return ResourceManager.GetString("lbl_Sccss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        public static string lbl_Search {
            get {
                return ResourceManager.GetString("lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string lbl_Send {
            get {
                return ResourceManager.GetString("lbl_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer un email.
        /// </summary>
        public static string lbl_SendEmail {
            get {
                return ResourceManager.GetString("lbl_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoi d&apos;Email.
        /// </summary>
        public static string lbl_SendingEmail {
            get {
                return ResourceManager.GetString("lbl_SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string lbl_Settings {
            get {
                return ResourceManager.GetString("lbl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrégée (Liste).
        /// </summary>
        public static string lbl_ShortDesc {
            get {
                return ResourceManager.GetString("lbl_ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Connecter.
        /// </summary>
        public static string lbl_SignIn {
            get {
                return ResourceManager.GetString("lbl_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se Déconnecter.
        /// </summary>
        public static string lbl_SignOut {
            get {
                return ResourceManager.GetString("lbl_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionez un Projet.
        /// </summary>
        public static string lbl_SlctProj {
            get {
                return ResourceManager.GetString("lbl_SlctProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionez une Propriétée.
        /// </summary>
        public static string lbl_SlctProp {
            get {
                return ResourceManager.GetString("lbl_SlctProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quelque chose ne va pas.
        /// </summary>
        public static string lbl_SmthngWrng {
            get {
                return ResourceManager.GetString("lbl_SmthngWrng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de Départ.
        /// </summary>
        public static string lbl_StartDate {
            get {
                return ResourceManager.GetString("lbl_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lbl_Status {
            get {
                return ResourceManager.GetString("lbl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lbl_Type {
            get {
                return ResourceManager.GetString("lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string lbl_Undo {
            get {
                return ResourceManager.GetString("lbl_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        public static string lbl_Unknown {
            get {
                return ResourceManager.GetString("lbl_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Profile.
        /// </summary>
        public static string lbl_UpdateProfile {
            get {
                return ResourceManager.GetString("lbl_UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger.
        /// </summary>
        public static string lbl_Upload {
            get {
                return ResourceManager.GetString("lbl_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion d&apos;Utilisateurs.
        /// </summary>
        public static string lbl_UserManagement {
            get {
                return ResourceManager.GetString("lbl_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom Utilisateur.
        /// </summary>
        public static string lbl_UsrNm {
            get {
                return ResourceManager.GetString("lbl_UsrNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom Utilisateur ou Email.
        /// </summary>
        public static string lbl_UsrNmEmail {
            get {
                return ResourceManager.GetString("lbl_UsrNmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours de Verification.
        /// </summary>
        public static string lbl_Verifying {
            get {
                return ResourceManager.GetString("lbl_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vues.
        /// </summary>
        public static string lbl_Views {
            get {
                return ResourceManager.GetString("lbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les Sous Produits.
        /// </summary>
        public static string lbl_VwSubProds {
            get {
                return ResourceManager.GetString("lbl_VwSubProds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avertissement.
        /// </summary>
        public static string lbl_Warning {
            get {
                return ResourceManager.GetString("lbl_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Web.
        /// </summary>
        public static string lbl_Website {
            get {
                return ResourceManager.GetString("lbl_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string lbl_Yes {
            get {
                return ResourceManager.GetString("lbl_Yes", resourceCulture);
            }
        }
    }
}
